trigger:
  - master
  - dev
  
pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Python36:
      python.version: '3.6'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python $(python.version)'
  inputs:
    versionSpec: '$(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python scripts/create_heatmap.py
  env:
    STRAVA_ACCESS_TOKEN: $(strava.access.token)
    STRAVA_CLIENT_ID: $(strava.client.id)
    STRAVA_CLIENT_SECRET: $(strava.client.secret)
    STRAVA_REFRESH_TOKEN: $(strava.refresh.token)
  displayName: 'Build html heatmap'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  inputs:
    containerRegistry: 'docker-connection'
    repository: 'rafaelschlatter/stravaheatmap'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
